In [ ]:
import pandas as pd

In [ ]:
tweets=pd.read_csv('/content/IRAhandle_tweets_1.csv')

In [ ]:
tweets=tweets.head(10000)

In [ ]:
english_tweets=tweets[tweets['language']=='English']

In [ ]:
english_tweets_noquestions=english_tweets[~english_tweets['content'].str.contains('\?',case=False)]

In [ ]:
english_tweets.to_csv('data_collection.tsv', sep="\t")

In [ ]:
english_tweets_noquestions

,external_author_id,author,content,region,language,publish_date,harvested_date,following,followers,updates,...,account_type,retweet,account_category,new_june_2018,alt_external_id,tweet_id,article_url,tco1_step1,tco2_step1,tco3_step1
0,906000000000000000,10_GOP,"""We have a sitting Democrat US Senator on tria...",Unknown,English,10/1/2017 19:58,10/1/2017 19:59,1052,9636,253,...,Right,0,RightTroll,0,905874659358453760,914580356430536707,http://twitter.com/905874659358453760/statuses...,https://twitter.com/10_gop/status/914580356430...,NaN,NaN
1,906000000000000000,10_GOP,Marshawn Lynch arrives to game in anti-Trump s...,Unknown,English,10/1/2017 22:43,10/1/2017 22:43,1054,9637,254,...,Right,0,RightTroll,0,905874659358453760,914621840496189440,http://twitter.com/905874659358453760/statuses...,https://twitter.com/damienwoody/status/9145685...,NaN,NaN
2,906000000000000000,10_GOP,Daughter of fallen Navy Sailor delivers powerf...,Unknown,English,10/1/2017 22:50,10/1/2017 22:51,1054,9637,255,...,Right,1,RightTroll,0,905874659358453760,914623490375979008,http://twitter.com/905874659358453760/statuses...,https://twitter.com/10_gop/status/913231923715...,NaN,NaN
3,906000000000000000,10_GOP,JUST IN: President Trump dedicates Presidents ...,Unknown,English,10/1/2017 23:52,10/1/2017 23:52,1062,9642,256,...,Right,0,RightTroll,0,905874659358453760,914639143690555392,http://twitter.com/905874659358453760/statuses...,https://twitter.com/10_gop/status/914639143690...,NaN,NaN
4,906000000000000000,10_GOP,"19,000 RESPECTING our National Anthem! #StandF...",Unknown,English,10/1/2017 2:13,10/1/2017 2:13,1050,9645,246,...,Right,1,RightTroll,0,905874659358453760,914312219952861184,http://twitter.com/905874659358453760/statuses...,https://twitter.com/realDonaldTrump/status/914...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7970,3312143142,4MYSQUAD,'@ShaunKing strange days are better than borin...,United States,English,8/21/2015 22:51,8/21/2015 22:51,1638,297,477,...,Left,0,LeftTroll,0,3312143142,634860489605021696,http://twitter.com/4mysquad/statuses/634860489...,NaN,NaN,NaN
7971,3312143142,4MYSQUAD,'@Didactic_1 @sluggoD54 @ShaunKing Now he hate...,United States,English,8/21/2015 22:55,8/21/2015 22:55,1647,297,478,...,Left,0,LeftTroll,0,3312143142,634861395679514624,http://twitter.com/4mysquad/statuses/634861395...,NaN,NaN,NaN
7973,3312143142,4MYSQUAD,'@AyoRetOfficial RIP the justice system is bro...,United States,English,8/21/2015 23:00,8/21/2015 23:00,1648,297,481,...,Left,0,LeftTroll,0,3312143142,634862594323578880,http://twitter.com/4mysquad/statuses/634862594...,NaN,NaN,NaN
7974,3312143142,4MYSQUAD,OMG! 9 y/o shot dead in ferguson while sitting...,United States,English,8/21/2015 2:30,8/21/2015 2:30,1240,253,344,...,Left,0,LeftTroll,0,3312143142,634553032861069312,http://twitter.com/4mysquad/statuses/634553032...,https://twitter.com/4mysquad/status/6345530328...,http://www.people.com/article/9-year-old-jamyl...,NaN
7975,3312143142,4MYSQUAD,No one cares #SandraBland #sandrablandvideo #B...,United States,English,8/21/2015 7:18,8/21/2015 7:18,1240,254,345,...,Left,0,LeftTroll,0,3312143142,634625535574831104,http://twitter.com/4mysquad/s,NaN,NaN,NaN

In [ ]:
english_tweets_noquestions['trump_mention']=''

<ipython-input-26-223bb427d8eb>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  english_tweets_noquestions['trump_mention']=''

In [ ]:
for a in english_tweets_noquestions['content']:
  d=english_tweets_noquestions.index.get_loc(english_tweets_noquestions.index[english_tweets_noquestions['content'] == a][0])
  if a.__contains__('Trump')==True:
    n=a.index('Trump')
    p=n+5
    y=str(a[n-1])
    if a.endswith('Trump') and y.isalnum()==False:
      english_tweets_noquestions.iloc[d,21]='T'
    else:
      x=str(a[p])
      y=str(a[n-1])
      if a.startswith('Trump') and x.isalnum()==False:
        english_tweets_noquestions.iloc[d,21]='T'
      elif x.isalnum()==False and y.isalnum()==False:
        english_tweets_noquestions.iloc[d,21]='T'
  else:
    english_tweets_noquestions.iloc[d,21]='F'

In [ ]:
english_tweets_noquestions['trump_mention']

0       F
1       T
2       F
3       T
4       F
       ..
7970    F
7971    T
7973    F
7974    F
7975    F
Name: trump_mention, Length: 3045, dtype: object

In [ ]:
def trump_check(a):
  d=english_tweets_noquestions.index.get_loc(english_tweets_noquestions.index[english_tweets_noquestions['content'] == a][0])
  if a.__contains__('Trump')==True:
    n=a.index('Trump')
    p=n+5
    y=str(a[n-1])
    if a.endswith('Trump') and y.isalnum()==False:
      english_tweets_noquestions.iloc[d,21]='T'
    else:
      x=str(a[p])
      y=str(a[n-1])
      if a.startswith('Trump') and x.isalnum()==False:
        english_tweets_noquestions.iloc[d,21]='T'
      elif x.isalnum()==False and y.isalnum()==False:
        english_tweets_noquestions.iloc[d,21]='T'
  else:
    english_tweets_noquestions.iloc[d,21]='F'

In [ ]:
english_tweets_noquestions['content'].apply(trump_check)

0       None
1       None
2       None
3       None
4       None
        ...
7970    None
7971    None
7973    None
7974    None
7975    None
Name: content, Length: 3045, dtype: object

In [ ]:
english_tweets_noquestions_trumpmention=english_tweets_noquestions[['tweet_id','publish_date','content','trump_mention']]

In [ ]:
english_tweets_noquestions_trumpmention.to_csv('dataset.tsv',sep='\t',header=True)

In [ ]:
english_tweets_noquestions_trumpmention.to_csv('dataset.csv',header=True)

## Ques 3

In [ ]:
val=len(english_tweets_noquestions_trumpmention[english_tweets_noquestions_trumpmention['trump_mention']=='T'])/len(english_tweets_noquestions_trumpmention['trump_mention'])
val=val*100
val=round(val,3)
val

2.989

In [ ]:
len(english_tweets_noquestions_trumpmention[english_tweets_noquestions_trumpmention['trump_mention']=='T'])

91

In [ ]:
new_file=pd.DataFrame([["fract_trump_mentions",val]],columns=['result','value'])

In [ ]:
new_file.loc[:,'result']="fract_trump_mentions"

In [ ]:
new_file

                 result  value
0  fract_trump_mentions  2.989

In [ ]:
new_file.to_csv('results.tsv',sep='\t',header=True)